Repository BOOK-TALK/Readables-Server, pull requests merged in 2024-07, with the labels that each got.

#9 #6 spring security
  src/main/java/com/book/backend/domain/auth/service/CustomUserDetailsService.java
  src/main/java/com/book/backend/exception/CustomException.java
  src/main/java/com/book/backend/exception/ErrorCode.java
  src/main/java/com/book/backend/global/SecurityConfig.java
Labels: ⭐️ Feature, 🥇 Urgency 1

#17 #13 cicd
  build.gradle
  deploy.sh
  docker-compose.yml
  src/main/resources/application.yml
Labels: 🌏 Deploy

#21 #20 data.sql
  src/main/resources/application.yml
  src/main/resources/data.sql
Labels: ⚙️ Setting

#15 #10 auth service
  build.gradle
  src/main/java/com/book/backend/domain/auth/controller/AuthController.java
  src/main/java/com/book/backend/domain/auth/dto/LoginDto.java
  src/main/java/com/book/backend/domain/auth/dto/SignupDto.java
  src/main/java/com/book/backend/domain/auth/mapper/AuthMapper.java
  src/main/java/com/book/backend/domain/auth/service/AuthService.java
  src/main/java/com/book/backend/domain/user/dto/UserDto.java
  src/main/java/com/book/backend/domain/user/entity/Gender.java
  src/main/java/com/book/backend/domain/user/entity/User.java
  src/main/java/com/book/backend/domain/user/mapper/UserMapper.java
  src/main/java/com/book/backend/exception/ErrorCode.java
  src/main/java/com/book/backend/global/ModelMapperConfig.java
  src/main/java/com/book/backend/global/SecurityConfig.java
  src/main/java/com/book/backend/global/SwaggerConfig.java
  src/main/resources/application.yml
Labels: ⭐️ Feature, 🥇 Urgency 1
