Repository BOOK-TALK/Readables-Server, pull requests merged in 2024-08, with the labels that each got.

#28 #23 log custom
  src/main/java/com/book/backend/domain/book/controller/BookController.java
  src/main/java/com/book/backend/domain/book/dto/TestDto.java
  src/main/java/com/book/backend/domain/book/service/BookService.java
  src/main/java/com/book/backend/global/WebConfig.java
  src/main/java/com/book/backend/global/log/LogBackConfig.java
  src/main/java/com/book/backend/global/log/LoggingInterceptor.java
  src/main/java/com/book/backend/global/log/RequestLogger.java
Labels: ⚙️ Setting

#33 #25 genre data initialization
  src/main/java/com/book/backend/domain/genre/controller/GenreController.java
  src/main/java/com/book/backend/domain/genre/entity/Genre.java
  src/main/java/com/book/backend/domain/genre/repository/GenreRepository.java
  src/main/java/com/book/backend/domain/genre/service/GenreService.java
  src/main/resources/import.sql
Labels: ⭐️ Feature, 🥇 Urgency 1

#34 #31 open api
  src/main/java/com/book/backend/domain/book/controller/BookController.java
  src/main/java/com/book/backend/domain/book/dto/TestDto.java
  src/main/java/com/book/backend/domain/book/service/BookService.java
  src/main/java/com/book/backend/domain/book/service/RequestValidate.java
  src/main/java/com/book/backend/domain/openapi/dto/request/HotTrendRequestDto.java
  src/main/java/com/book/backend/domain/openapi/dto/request/OpenAPIRequestInterface.java
  src/main/java/com/book/backend/domain/openapi/dto/request/RecommendRequestDto.java
  src/main/java/com/book/backend/domain/openapi/dto/response/HotTrendResponseDto.java
  src/main/java/com/book/backend/domain/openapi/dto/response/OpenAPIResponseInterface.java
  src/main/java/com/book/backend/domain/openapi/dto/response/RecommendResponseDto.java
  src/main/java/com/book/backend/domain/openapi/service/OpenAPI.java
  src/main/java/com/book/backend/domain/openapi/service/ResponseParser.java
  src/main/java/com/book/backend/exception/ErrorCode.java
  src/main/java/com/book/backend/exception/ExceptionHandlerResponse.java
  src/main/java/com/book/backend/global/ResponseTemplate.java
  src/main/resources/application.yml
  src/main/resources/import.sql
Labels: ⭐️ Feature, 🥇 Urgency 1

#35 #19 home main
  src/main/java/com/book/backend/domain/book/controller/BookController.java
  src/main/java/com/book/backend/domain/book/service/BookService.java
  src/main/java/com/book/backend/domain/book/service/RequestValidate.java
  src/main/java/com/book/backend/domain/openapi/dto/request/CustomHotTrendRequestDto.java
  src/main/java/com/book/backend/domain/openapi/dto/request/KeywordRequestDto.java
  src/main/java/com/book/backend/domain/openapi/dto/response/CustomHotTrendResponseDto.java
  src/main/java/com/book/backend/domain/openapi/dto/response/KeywordResponseDto.java
  src/main/java/com/book/backend/domain/openapi/entity/AgeRangeCode.java
  src/main/java/com/book/backend/domain/openapi/entity/RegionCode.java
  src/main/java/com/book/backend/domain/openapi/service/OpenAPI.java
  src/main/java/com/book/backend/domain/openapi/service/RandomPicker.java
  src/main/java/com/book/backend/domain/openapi/service/RequestValidate.java
  src/main/java/com/book/backend/domain/openapi/service/ResponseParser.java
  src/main/java/com/book/backend/exception/ErrorCode.java
  src/main/java/com/book/backend/global/log/RequestLogger.java
Labels: ⭐️ Feature

#37 #36 swagger
  src/main/java/com/book/backend/domain/book/controller/BookController.java
  src/main/java/com/book/backend/domain/openapi/dto/response/CustomHotTrendResponseDto.java
  src/main/java/com/book/backend/domain/openapi/dto/response/HotTrendResponseDto.java
  src/main/java/com/book/backend/domain/openapi/dto/response/KeywordResponseDto.java
  src/main/java/com/book/backend/domain/openapi/dto/response/RecommendResponseDto.java
Labels: 📄 Docs

#38 #26 genre api
  src/main/java/com/book/backend/domain/book/controller/BookController.java
  src/main/java/com/book/backend/domain/book/service/BookRequestValidate.java
  src/main/java/com/book/backend/domain/genre/controller/GenreController.java
  src/main/java/com/book/backend/domain/genre/service/GenreRequestValidate.java
  src/main/java/com/book/backend/domain/genre/service/GenreResponseParser.java
  src/main/java/com/book/backend/domain/genre/service/GenreService.java
  src/main/java/com/book/backend/domain/openapi/dto/request/LoanTrendRequestDto.java
  src/main/java/com/book/backend/domain/openapi/dto/response/HotTrendResponseDto.java
  src/main/java/com/book/backend/domain/openapi/dto/response/LoanTrendResponseDto.java
  src/main/java/com/book/backend/domain/openapi/dto/response/RecommendResponseDto.java
  src/main/java/com/book/backend/domain/openapi/service/ResponseParser.java
  src/main/java/com/book/backend/exception/ErrorCode.java
Labels: ⭐️ Feature, 🥈 Urgency 2

#44 #42 refactor main
  src/main/java/com/book/backend/domain/book/controller/BookController.java
  src/main/java/com/book/backend/domain/book/service/BookRequestValidate.java
  src/main/java/com/book/backend/domain/book/service/BookService.java
  src/main/java/com/book/backend/domain/genre/controller/GenreController.java
  src/main/java/com/book/backend/domain/genre/service/GenreRequestValidate.java
  src/main/java/com/book/backend/domain/genre/service/GenreResponseParser.java
  src/main/java/com/book/backend/domain/genre/service/GenreService.java
  src/main/java/com/book/backend/domain/openapi/dto/request/LoanItemSrchRequestDto.java
  src/main/java/com/book/backend/domain/openapi/dto/request/LoanTrendRequestDto.java
  src/main/java/com/book/backend/domain/openapi/dto/request/MonthlyKeywordsRequestDto.java
  src/main/java/com/book/backend/domain/openapi/dto/request/RecommendListRequestDto.java
  src/main/java/com/book/backend/domain/openapi/dto/response/LoanItemSrchResponseDto.java
  src/main/java/com/book/backend/domain/openapi/dto/response/LoanTrendResponseDto.java
  src/main/java/com/book/backend/domain/openapi/dto/response/MonthlyKeywordsResponseDto.java
  src/main/java/com/book/backend/domain/openapi/dto/response/RecommendListResponseDto.java
  src/main/java/com/book/backend/domain/openapi/service/RandomPicker.java
  src/main/java/com/book/backend/domain/openapi/service/RequestValidate.java
  src/main/java/com/book/backend/domain/openapi/service/ResponseParser.java
Labels: ✨ Refactor, 🥉 Urgency 3, 🔧 Fix

#43 #40 책 검색, 책 상세 API
  src/main/java/com/book/backend/domain/detail/controller/DetailController.java
  src/main/java/com/book/backend/domain/detail/dto/BookInfoDto.java
  src/main/java/com/book/backend/domain/detail/dto/CoLoanBooksDto.java
  src/main/java/com/book/backend/domain/detail/dto/KeywordDto.java
  src/main/java/com/book/backend/domain/detail/dto/LoanHistoryDto.java
  src/main/java/com/book/backend/domain/detail/dto/RecommendDto.java
  src/main/java/com/book/backend/domain/detail/dto/Top3LoanUserDto.java
  src/main/java/com/book/backend/domain/detail/service/DetailService.java
  src/main/java/com/book/backend/domain/openapi/dto/request/BookExistRequestDto.java
  src/main/java/com/book/backend/domain/openapi/dto/request/DetailRequestDto.java
  src/main/java/com/book/backend/domain/openapi/dto/request/SearchRequestDto.java
  src/main/java/com/book/backend/domain/openapi/dto/response/BookExistResponseDto.java
  src/main/java/com/book/backend/domain/openapi/dto/response/DetailResponseDto.java
  src/main/java/com/book/backend/domain/openapi/dto/response/SearchResponseDto.java
  src/main/java/com/book/backend/domain/openapi/service/OpenAPI.java
  src/main/java/com/book/backend/domain/openapi/service/RequestValidate.java
  src/main/java/com/book/backend/domain/openapi/service/ResponseParser.java
  src/main/java/com/book/backend/domain/search/controller/SearchController.java
  src/main/java/com/book/backend/domain/search/dto/RequestDto.java
  src/main/java/com/book/backend/domain/search/service/SearchService.java
  src/main/java/com/book/backend/exception/ErrorCode.java
Labels: ⭐️ Feature

#48 [refactor] 장르 컨트롤러에 pageNo, pageSize 파라미터 추가
  src/main/java/com/book/backend/domain/genre/controller/GenreController.java
  src/main/java/com/book/backend/domain/genre/service/GenreResponseParser.java
  src/main/java/com/book/backend/domain/genre/service/GenreService.java
Labels: ✨ Refactor, 🥉 Urgency 3

#49 #46 opentalk
  src/main/java/com/book/backend/domain/libcode/entity/Libcode.java
  src/main/java/com/book/backend/domain/message/entity/Message.java
  src/main/java/com/book/backend/domain/message/repository/MessageRepository.java
  src/main/java/com/book/backend/domain/opentalk/OpentalkResponseDto.java
  src/main/java/com/book/backend/domain/opentalk/controller/OpentalkController.java
  src/main/java/com/book/backend/domain/opentalk/entity/Opentalk.java
  src/main/java/com/book/backend/domain/opentalk/service/OpentalkService.java
  src/main/java/com/book/backend/domain/user/entity/User.java
  src/main/java/com/book/backend/domain/user/repository/UserRepository.java
  src/main/java/com/book/backend/domain/userLibcode/entity/UserLibcode.java
  src/main/java/com/book/backend/domain/userOpentalk/entity/UserOpentalk.java
  src/main/java/com/book/backend/domain/userOpentalk/repository/UserOpentalkRepository.java
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/main/resources/dummy.sql
Labels: ⭐️ Feature

#51 #41 oauth kakao
  src/main/java/com/book/backend/domain/auth/controller/AuthController.java
  src/main/java/com/book/backend/domain/auth/dto/KakaoTokenResponseDto.java
  src/main/java/com/book/backend/domain/auth/dto/KakaoUserInfoDto.java
  src/main/java/com/book/backend/domain/auth/service/CustomUserDetailsService.java
  src/main/java/com/book/backend/domain/auth/service/KakaoService.java
  src/main/java/com/book/backend/domain/user/dto/UserDto.java
  src/main/java/com/book/backend/domain/user/entity/User.java
  src/main/java/com/book/backend/domain/user/repository/UserRepository.java
  src/main/java/com/book/backend/exception/ErrorCode.java
  src/main/java/com/book/backend/global/AuthConfig.java
  src/main/java/com/book/backend/global/SecurityConfig.java
  src/main/resources/application.yml
Labels: ⭐️ Feature, 🥇 Urgency 1

#58 #54 edit api format 2
  src/main/java/com/book/backend/domain/auth/service/JwtAuthenticationFilter.java
  src/main/java/com/book/backend/exception/ErrorCode.java
  src/main/java/com/book/backend/global/CustomAuthenticationEntryPoint.java
Labels: ✨ Refactor, 🥉 Urgency 3

#61 #60 custom page filter
  src/main/java/com/book/backend/domain/genre/controller/GenreController.java
  src/main/java/com/book/backend/domain/genre/service/GenreResponseParser.java
  src/main/java/com/book/backend/domain/genre/service/GenreService.java
  src/main/java/com/book/backend/domain/openapi/service/ResponseParser.java
Labels: ⭐️ Feature, 🥉 Urgency 3

#65 [refactor] aWeekTrend, aMonthTrend API에 커스텀 페이지네이션 적용
  src/main/java/com/book/backend/domain/genre/controller/GenreController.java
  src/main/java/com/book/backend/domain/genre/service/GenreResponseParser.java
  src/main/java/com/book/backend/domain/genre/service/GenreService.java
Labels: 🥉 Urgency 3, 🔧 Fix

#74 #66 refactor
  src/main/java/com/book/backend/domain/opentalk/controller/OpentalkController.java
  src/main/java/com/book/backend/domain/search/controller/SearchController.java
  src/main/java/com/book/backend/domain/search/service/SearchService.java
Labels: ⭐️ Feature

#76 [chore] email, phone 필드 제거
  src/main/java/com/book/backend/domain/auth/dto/SignupDto.java
  src/main/java/com/book/backend/domain/user/dto/UserDto.java
  src/main/java/com/book/backend/domain/user/entity/User.java
  src/main/java/com/book/backend/domain/user/repository/UserRepository.java
  src/main/resources/dummy.sql
Labels: ✨ Refactor, 🥉 Urgency 3

#78 #77 add kakao login dto field
  src/main/java/com/book/backend/domain/auth/controller/AuthController.java
  src/main/java/com/book/backend/domain/auth/dto/LoginSuccessResponseDto.java
  src/main/java/com/book/backend/domain/auth/service/KakaoService.java
Labels: ⭐️ Feature, 🥉 Urgency 3

#80 8/21 수정사항 (책 상세)
  src/main/java/com/book/backend/domain/detail/controller/DetailController.java
  src/main/java/com/book/backend/domain/detail/dto/LoanAvailableDto.java
  src/main/java/com/book/backend/domain/detail/service/DetailService.java
  src/main/java/com/book/backend/domain/openapi/dto/response/DetailResponseDto.java
  src/main/java/com/book/backend/domain/user/service/UserService.java
Labels: 🔧 Fix

#85 #83 library name
  src/main/java/com/book/backend/domain/detail/service/DetailService.java
  src/main/java/com/book/backend/domain/user/controller/UserController.java
  src/main/java/com/book/backend/domain/user/dto/LibraryDto.java
  src/main/java/com/book/backend/domain/user/dto/UserLibrariesRequestDto.java
  src/main/java/com/book/backend/domain/user/dto/UserLibrariesResponseDto.java
  src/main/java/com/book/backend/domain/user/entity/User.java
  src/main/java/com/book/backend/domain/user/service/UserService.java
  src/main/java/com/book/backend/exception/ErrorCode.java
Labels: ⭐️ Feature, 🥈 Urgency 2

#92 #90 refactor log
  src/main/java/com/book/backend/domain/auth/controller/AuthController.java
  src/main/java/com/book/backend/domain/auth/service/AuthService.java
  src/main/java/com/book/backend/domain/auth/service/CustomUserDetailsService.java
  src/main/java/com/book/backend/domain/auth/service/JwtAuthenticationFilter.java
  src/main/java/com/book/backend/domain/auth/service/JwtRefreshTokenService.java
  src/main/java/com/book/backend/domain/auth/service/KakaoService.java
  src/main/java/com/book/backend/domain/book/controller/BookController.java
  src/main/java/com/book/backend/domain/book/service/BookService.java
  src/main/java/com/book/backend/domain/detail/controller/DetailController.java
  src/main/java/com/book/backend/domain/detail/service/DetailService.java
  src/main/java/com/book/backend/domain/genre/controller/GenreController.java
  src/main/java/com/book/backend/domain/genre/service/GenreService.java
  src/main/java/com/book/backend/domain/library/controller/LibraryController.java
  src/main/java/com/book/backend/domain/openapi/service/RequestValidate.java
  src/main/java/com/book/backend/domain/opentalk/controller/OpentalkController.java
  src/main/java/com/book/backend/domain/opentalk/service/OpentalkService.java
  src/main/java/com/book/backend/domain/search/controller/SearchController.java
  src/main/java/com/book/backend/domain/search/service/SearchService.java
  src/main/java/com/book/backend/domain/user/controller/UserController.java
  src/main/java/com/book/backend/domain/user/service/UserService.java
  src/main/java/com/book/backend/domain/userBook/controller/UserBookController.java
  src/main/java/com/book/backend/domain/userBook/service/UserBookService.java
  src/main/java/com/book/backend/global/ResponseTemplate.java
  src/main/java/com/book/backend/global/log/LogBackConfig.java
  src/main/resources/application.yml
Labels: 📄 Docs, ✨ Refactor

#91 #87 OIDC setting
  src/main/java/com/book/backend/domain/auth/controller/AuthController.java
  src/main/java/com/book/backend/domain/auth/dto/KakaoTokenResponseDto.java
  src/main/java/com/book/backend/domain/auth/service/KakaoService.java
  src/main/java/com/book/backend/domain/oidc/OidcProvider.java
  src/main/java/com/book/backend/domain/oidc/OidcProviderFactory.java
  src/main/java/com/book/backend/domain/oidc/Provider.java
  src/main/java/com/book/backend/domain/oidc/PublicKeyProvider.java
  src/main/java/com/book/backend/domain/oidc/kakao/KakaoAuthClient.java
  src/main/java/com/book/backend/domain/oidc/kakao/KakaoAuthProvider.java
  src/main/java/com/book/backend/domain/oidc/record/OidcPublicKey.java
  src/main/java/com/book/backend/domain/oidc/record/OidcPublicKeyList.java
  src/main/java/com/book/backend/domain/user/controller/UserController.java
  src/main/java/com/book/backend/exception/ErrorCode.java
  src/main/java/com/book/backend/global/RestClientConfig.java
  src/main/java/com/book/backend/util/JwtUtil.java
  src/main/resources/application.yml
Labels: ⭐️ Feature, 🥇 Urgency 1

#94 #93 fix decoding
  src/main/java/com/book/backend/domain/auth/service/AuthService.java
  src/main/java/com/book/backend/domain/auth/service/KakaoService.java
  src/main/java/com/book/backend/domain/user/service/UserService.java
  src/main/java/com/book/backend/exception/ErrorCode.java
Labels: 🥈 Urgency 2, 🔧 Fix

#96 #64 apple oauth2
  src/main/java/com/book/backend/domain/auth/controller/AuthController.java
  src/main/java/com/book/backend/domain/auth/service/AppleService.java
  src/main/java/com/book/backend/domain/auth/service/AuthService.java
  src/main/java/com/book/backend/domain/auth/service/CustomUserDetailsService.java
  src/main/java/com/book/backend/domain/auth/service/JwtAuthenticationFilter.java
  src/main/java/com/book/backend/domain/oidc/OidcProviderFactory.java
  src/main/java/com/book/backend/domain/oidc/apple/AppleAuthClient.java
  src/main/java/com/book/backend/domain/oidc/apple/AppleAuthProvider.java
  src/main/java/com/book/backend/domain/user/dto/UserDto.java
  src/main/java/com/book/backend/domain/user/entity/User.java
  src/main/java/com/book/backend/domain/user/repository/UserRepository.java
  src/main/java/com/book/backend/domain/user/service/UserService.java
  src/main/java/com/book/backend/exception/ErrorCode.java
  src/main/java/com/book/backend/global/SecurityConfig.java
  src/main/resources/application.yml
Labels: ⭐️ Feature, 🥇 Urgency 1

#95 #71 stomp
  src/main/java/com/book/backend/domain/message/controller/MessageController.java
  src/main/java/com/book/backend/domain/message/dto/MessageRequestDto.java
  src/main/java/com/book/backend/domain/message/mapper/MessageMapper.java
  src/main/java/com/book/backend/domain/message/service/MessageService.java
  src/main/java/com/book/backend/domain/opentalk/controller/OpentalkController.java
  src/main/java/com/book/backend/domain/opentalk/service/OpentalkService.java
  src/main/java/com/book/backend/global/SecurityConfig.java
  src/main/java/com/book/backend/global/stomp/WebSocketConfig.java
Labels: ⭐️ Feature, 🥇 Urgency 1

#103 #102 favorite opentalk
  src/main/java/com/book/backend/domain/message/controller/MessageController.java
  src/main/java/com/book/backend/domain/message/dto/MessageRequestDto.java
  src/main/java/com/book/backend/domain/message/service/MessageService.java
  src/main/java/com/book/backend/domain/opentalk/controller/OpentalkController.java
  src/main/java/com/book/backend/domain/opentalk/service/OpentalkService.java
  src/main/java/com/book/backend/domain/userOpentalk/repository/UserOpentalkRepository.java
  src/main/java/com/book/backend/exception/ErrorCode.java
Labels: ⭐️ Feature

#105 #104 read book
  src/main/java/com/book/backend/domain/search/service/SearchService.java
  src/main/java/com/book/backend/domain/user/controller/UserController.java
  src/main/java/com/book/backend/domain/user/dto/MyPageDto.java
  src/main/java/com/book/backend/domain/user/entity/User.java
  src/main/java/com/book/backend/domain/userBook/controller/UserBookController.java
  src/main/java/com/book/backend/domain/userBook/service/UserBookService.java
  src/main/resources/sql/dummy.sql
Labels: ⭐️ Feature

#110 #108 token blacklist
  src/main/java/com/book/backend/domain/auth/controller/AuthController.java
  src/main/java/com/book/backend/domain/auth/service/AuthService.java
  src/main/java/com/book/backend/exception/ErrorCode.java
  src/main/java/com/book/backend/global/JwtAuthenticationFilter.java
  src/main/java/com/book/backend/util/JwtUtil.java
Labels: ⭐️ Feature, 🥇 Urgency 1

#114 [fix] 회원탈퇴 API 오류 해결
  src/main/java/com/book/backend/domain/user/entity/User.java
Labels: 🥉 Urgency 3, 🔧 Fix

#112 #111 8/25 수정사항
  src/main/java/com/book/backend/domain/detail/controller/DetailController.java
  src/main/java/com/book/backend/domain/openapi/dto/response/DetailResponseDto.java
  src/main/java/com/book/backend/domain/opentalk/service/OpentalkService.java
  src/main/java/com/book/backend/domain/userBook/service/UserBookService.java
  src/main/java/com/book/backend/exception/ErrorCode.java
  src/main/java/com/book/backend/global/SwaggerConfig.java
  src/main/resources/application.yml
Labels: 🔧 Fix

#120 [feat] ResponseParser에 중복 방지 로직 추가
  src/main/java/com/book/backend/domain/openapi/service/ResponseParser.java
Labels: ⭐️ Feature, 🥉 Urgency 3

#126 #122 opentalk share goal
  src/main/java/com/book/backend/domain/message/controller/MessageController.java
  src/main/java/com/book/backend/domain/message/dto/MessageRequestDto.java
  src/main/java/com/book/backend/domain/message/dto/MessageResponseDto.java
  src/main/java/com/book/backend/domain/message/entity/Message.java
  src/main/java/com/book/backend/domain/message/mapper/MessageMapper.java
  src/main/java/com/book/backend/domain/message/service/MessageService.java
  src/main/java/com/book/backend/domain/openapi/service/RequestValidate.java
  src/main/java/com/book/backend/exception/ErrorCode.java
Labels: ⭐️ Feature

#130 #129 users in goal
  src/main/java/com/book/backend/domain/goal/controller/GoalController.java
  src/main/java/com/book/backend/domain/goal/dto/UserGoalDto.java
  src/main/java/com/book/backend/domain/goal/dto/UserProgressDto.java
  src/main/java/com/book/backend/domain/goal/repository/GoalRepository.java
  src/main/java/com/book/backend/domain/goal/service/GoalService.java
Labels: ⭐️ Feature, 🥈 Urgency 2

#132 #131 fix goal api
  src/main/java/com/book/backend/domain/goal/controller/GoalController.java
  src/main/java/com/book/backend/domain/goal/dto/MyProgressDto.java
  src/main/java/com/book/backend/domain/goal/dto/UserProgressDto.java
  src/main/java/com/book/backend/domain/goal/mapper/GoalMapper.java
  src/main/java/com/book/backend/domain/goal/service/GoalService.java
Labels: ⭐️ Feature, 🥉 Urgency 3

#133 Record
  src/main/java/com/book/backend/domain/goal/entity/Goal.java
  src/main/java/com/book/backend/domain/goal/mapper/GoalMapper.java
  src/main/java/com/book/backend/domain/goal/service/GoalRecordsService.java
  src/main/java/com/book/backend/domain/goal/service/GoalService.java
  src/main/java/com/book/backend/domain/record/dto/RecordDto.java
  src/main/java/com/book/backend/domain/record/entity/Record.java
  src/main/java/com/book/backend/domain/record/mapper/RecordMapper.java
  src/main/java/com/book/backend/domain/record/repository/RecordRepository.java
  src/main/resources/application.yml
  src/main/resources/sql/dummy.sql
Labels: ✨ Refactor
